definitions:
  steps:
    - step: &Build-image-step
        name: Build docker images
        image: docker/compose:latest
        services:
          - docker
        caches:
          - docker
        script:
          - docker -v
          - docker login $ARTIFACTORY_URL -p $ARTIFACTORY_API_KEY -u $ARTIFACTORY_USER 
          - apk add git bash
          - chmod 777 scripts -R
          - cd scripts
          - pwd
          - ls -l
          - /bin/bash ./useDevelopmentSdk.sh
          - /bin/bash ./setupNpmrc.sh
          - cd ../
          - chmod 777 setup.sh
          - docker-compose -v
          - docker-compose build --build-arg IMAGECAPTURE_SDK_NPM_AUTH_TOKEN=$IMAGECAPTURE_SDK_NPM_AUTH_TOKEN
          - docker tag $SAMPLE_APP_IMAGE_NAME $ARTIFACTORY_URL/$SAMPLE_APP_IMAGE_NAME
          - docker tag $SAMPLE_APP_IMAGE_NAME $ARTIFACTORY_URL/$SAMPLE_APP_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER
          - docker push $ARTIFACTORY_URL/$SAMPLE_APP_IMAGE_NAME
          - docker push $ARTIFACTORY_URL/$SAMPLE_APP_IMAGE_NAME:$BITBUCKET_BUILD_NUMBER
    - step: &Deploy-step
        name: Deploy images
        image: hashicorp/terraform:light
        script:
          - cd terraformControl
          - export TF_VAR_ARTIFACTORY_URL=$ARTIFACTORY_URL
          - export TF_VAR_ARTIFACTORY_REG_CRED=$ARTIFACTORY_REG_CRED
          - export TF_VAR_BUILD_VERSION=$BITBUCKET_BUILD_NUMBER
          - export TF_VAR_SAMPLE_APP_IMAGE_NAME=$SAMPLE_APP_IMAGE_NAME
          - terraform init -force-copy -input=false
          - terraform validate
          - terraform get --update
          - terraform apply -input=false -auto-approve
pipelines:
  pull-requests:
    '**':
      - step:
          name: Begin PR pipeline deployment
          script:
            - echo "For manual deployment in PRs please activate the below steps in order"
      - step: 
          <<: *Build-image-step
          trigger: manual
      - step: *Deploy-step
  branches:
    master:
      - step: *Build-image-step
      - step: *Deploy-step
